spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/uni_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      testOnBorrow: true 
      validationQuery: select 1 from dual
      max-wait: 10000
      max-active: 50
      test-on-borrow: true